version: '3'
services:
  rtsp-to-web:
    image: ghcr.io/deepch/rtsptoweb:latest 
    container_name: rtsp-to-web
    ports:
      - 8083:8083
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config.json:/config/config.json
volumes:
  config: